### ISSUE TITLE
Hexo upgrade to 4.0.0, the created URL is wrong.

### ISSUE THREAD

**Issue by carl0schen** [hexojs/hexo-generator-sitemap#75]
Found a lot of URLs with incorrect search in google search console, check that the url in sitemap.xml is wrong.

EX.
Wrong url: `https://blog.abc.com/Tasker%25E6%258E%25A7%25E5%2588%25B6AdGuard%25E9%2596%258B%25E9%2597%259C/`
Correct url: `https://blog.abc.com/Tasker%E6%8E%A7%E5%88%B6AdGuard%E9%96%8B%E9%97%9C/`

Later, refer to the method here to solve the problem that the sitemap creates the wrong url.
http://www.frozenluo.club/2019/04/15/abouttogoogle/

Version:
<img width="682" alt="hexo_v" src="https://user-images.githubusercontent.com/18241068/67823448-26235e00-fafe-11e9-925b-200602af2e09.png">
<img width="499" alt="package_json" src="https://user-images.githubusercontent.com/18241068/67823462-2e7b9900-fafe-11e9-90b6-4c53da2acedf.png">

**Comment by tomap** [comment]
Hi, could you provide your _config.yml file?

**Comment by carl0schen** [comment]
My `_config.yml` file:
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Carlos Life Book
subtitle:
description: Carlos的個人網誌，本站記錄有關網路、電玩、軟體、硬體等個人心得資料。
author: Carlos
language: zh-TW
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://carlos.my-net.tw
enforce_ssl: carlos.my-net.tw
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - .htaccess
  - 403.html
  - 404.html
  - robots.txt
  - yandex_fdf45e37dfae5d5a.html
  - yandex_80963f30fcc34c64.html
include:
  - .htaccess

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true

highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: light

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# Disqus
disqus_shortname: carloschen

## Plugins
# RSS
feed:
  type: atom
  path: atom.xml
  limit: 10
# Sitemap
sitemap:
    path: sitemap.xml
# nofollow
nofollow:
    enable: true
    exclude:
    - my-net.tw
    - alinn.my-net.tw
    - carlos.my-net.tw
# Flick
flickr_api_key: d3600d993fe0bfd380ded6ea8162db3e
# Enable Flickr Cache file
flickr_cache_file_path: hexo-tag-flickr-cache.json
flickr_cache_expires: 2592000000
```
